apiVersion: v1
kind: Service
metadata:
 name: nginx
 labels:
   app: nginx
spec:
 type: ClusterIP
 selector:
   app: nginx
 ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smoketestpod-cm
  labels:
    app: smoketestpod-cm
data:
  VARCONGIFMAP: "configmap-test"
---
apiVersion: v1
kind: Secret
metadata:
  name: smoketestpod-secret
  labels:
    app: smoketestpod-secret
type: Opaque
data:
  VARSECRET: "bXlzZWNyZXR2YXQ="
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  # triggers:
  #   - type: "ConfigChange"
  #   - type: "ImageChange" 
  #     imageChangeParams:
  #       automatic: true
  #       containerNames:
  #         - nginx
  #       from:
  #         kind: "ImageStreamTag"
  #         name: "image-registry.openshift-image-registry.svc:5000/openshift/nginx"
  paused: false   
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim: 
            claimName: smoketestpvc
      containers:
        - name: nginx
          image: "docker-registry.default.svc:5000/default/test@sha256:37b38e5af07007930f94d75b915c99c26976a4dbc0bc11108d43c181029ef776" 
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 20"]
          resources:
            requests:
              cpu: "100m"
              memory: "500Mi"
            limits:
              cpu: "200m"
              memory: "700Mi"
          env:
            - name: "CONFIGMAP-ENV"
              valueFrom:
                configMapKeyRef:
                  name: "smoketestpod-cm"
                  key: "VARCONGIFMAP"
            - name: "SECRET-ENV"
              valueFrom:
                secretKeyRef:
                  name: "smoketestpod-secret"
                  key: "VARSECRET"
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: pv-storage
          ports:
            - containerPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/host.generated: "true"
  labels:
    app: "nginx"
  name: "nginx"
spec:
  host: nginx-default.apps.clusterhouse-c4afa43ec152e314f7072ba02bde2f76-0001.us-south.containers.appdomain.cloud
  port:
    targetPort: 8080
  to:
    kind: Service
    name: "nginx"
    weight: 100
  wildcardPolicy: None
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "nginx"
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50